### ISSUE TITLE
I need more examples

### ISSUE THREAD

**Issue by XIOLog** [rainlab/notify-plugin#28]
Hello.

Have you got any more examples of how to use RainLab.Notify, please?

I'm interested in creating my own notifications, but you have an example for users only. I am confused and don`t understand anything.

Where can I see examples of how to write notifications from scratch using your plugin?

**Comment by LukeTowers** [comment]
Registering event listeners for the plugin in Plugin.php -> boot():
```php
\RainLab\Notify\Classes\Notifier::bindEvents([
    'captive.xm.shifts.staffmember.add' => \Captive\XM\Classes\Notify\Events\StaffAdded::class,
    'captive.xm.shifts.staffmember.remove' => \Captive\XM\Classes\Notify\Events\StaffRemoved::class
]);
```

Registering the custom plugin's support for the notify plugin in custom plugin's Plugin.php:
```php
public function registerNotificationRules()
    {
        return [
            'events' => [
                \Captive\XM\Classes\Notify\Events\StaffAdded::class,
                \Captive\XM\Classes\Notify\Events\StaffRemoved::class,
            ],
            'actions' => [
                \Captive\XM\Classes\Notify\Actions\SendEmail::class,
                \Captive\XM\Classes\Notify\Actions\SendSMS::class,
            ],
            'conditions' => [],
            'groups' => [
                'shifts' => [
                    'label' => 'Shifts',
                    'icon' => 'icon-calendar'
                ],
            ],
            'presets' => '$/captive/xm/classes/notify/presets.yaml',
        ];
    }
```

presets.yaml
```yaml
# ===================================
#  Event Presets
# ===================================

member_added:
    name: Member has been added to a shift
    event: Captive\XM\Classes\Notify\Events\StaffAdded
    items:
        - action: Captive\XM\Classes\Notify\Actions\SendSMS
          template: 'You are assigned to {{ shiftName }} - {{ eventName }} as a {{ role }} for {{ date }}. Details at {{ url }}'
        - action: Captive\XM\Classes\Notify\Actions\SendEmail
          mail_template: captive.xm::mail.shift.member_added
          file_name: myshift.ics
    conditions:
        - condition: RainLab\Notify\NotifyRules\ExecutionContextCondition
          subcondition: environment
          operator: is
          value: prod
          condition_text: Application environment <span class="operator">is</span> prod
member_removed:
    name: Member has been removed from a shift
    event: Captive\XM\Classes\Notify\Events\StaffRemoved
    items:
        - action: Captive\XM\Classes\Notify\Actions\SendSMS
          template: You have been removed from {{ shiftName }} - {{ eventName }} for {{ date }}.
        - action: Captive\XM\Classes\Notify\Actions\SendEmail
          mail_template: captive.xm::mail.shift.member_removed
    conditions:
        - condition: RainLab\Notify\NotifyRules\ExecutionContextCondition
          subcondition: environment
          operator: is
          value: prod
          condition_text: Application environment <span class="operator">is</span> prod
```

SendEmail.php action:
```php
<?php namespace Captive\XM\Classes\Notify\Actions;

use Mail;
use System\Models\MailTemplate;

class SendEmail extends \RainLab\Notify\Classes\ActionBase
{
    /**
     * Returns information about this event, including name and description.
     */
    public function actionDetails()
    {
        return [
            'name'        => 'Send an email',
            'description' => 'Send an email to a staff member',
            'icon'        => 'icon-envelope-o'
        ];
    }

    /**
     * Field configuration for the action.
     */
    public function defineFormFields()
    {
        return 'fields.yaml';
    }

    public function getText()
    {
        $template = $this->host->mail_template;

        return 'Send a message using template: ' . $template;
    }

    public function getMailTemplateOptions()
    {
        $codes = array_keys(MailTemplate::listAllTemplates());
        return array_combine($codes, $codes);;
    }

    /**
     * Triggers this action.
     * @param array $params
     * @return void
     */
    public function triggerAction($params)
    {
        $emailCode = $this->host->mail_template;
        $fileName  = $this->host->file_name;
        $staffMember = $params['staffmember'];
        $mailData = $params['mailData'];
        $fileData = $params['fileData'];

        Mail::queue($emailCode, $mailData, function ($message) use ($staffMember, $fileData, $fileName) {
            $message->to($staffMember->email, $staffMember->full_name);
            if (!empty($fileData)) {
                $message->attachData($fileData, $fileName);
            }
        });
    }
}
```
SendEmail.php fields.yaml:
```yaml
fields:
    mail_template:
        label: Mail template
        type: dropdown
        placeholder: Select template
    file_name:
        label: File Name
        type: text
        placeholder: The attached file name
```
StaffRemoved.php Event:
```php
<?php namespace Captive\XM\Classes\Notify\Events;

class StaffRemoved extends \RainLab\Notify\Classes\EventBase
{
    /**
     * Returns information about this event, including name and description.
     */
    public function eventDetails()
    {
        return [
            'name'        => 'Staff member removed',
            'description' => 'Fired when a staff member has been removed from a shift',
            'group'       => 'shifts'
        ];
    }

    /**
     * Defines the usable parameters provided by this class.
     */
    public function defineParams()
    {
        return [
            'name' => [
                'title' => 'Name',
                'label' => 'Name of the staff member',
            ],
            'shiftName' => [
                'title' => 'Shift',
                'label' => 'Name of the shift',
            ],
            'eventName' => [
                'title' => 'Event',
                'label' => 'Name of the event',
            ],
            'role' => [
                'title' => 'Role',
                'label' => 'Name of the role',
            ],
            'date' => [
                'title' => 'Start time',
                'label' => "The shift's start time",
            ],
            'url' => [
                'title' => 'URL',
                'label' => 'The URL for the shift',
            ],
        ];
    }

    public static function makeParamsFromEvent(array $args, $eventName = null)
    {
        return [
            'shiftslot'     => array_get($args, 0),
            'staffmember'   => array_get($args, 1),
            'mailData'      => array_get($args, 2),
            'fileData'      => null,
        ];
    }
}
```
`captive.xm.shifts.staffmember.remove` event fired in the ShiftSlot model:
```php
Event::fire('captive.xm.shifts.staffmember.remove', [$this, $member, $data]);
```
